name: update_benchmark

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 6 1 * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  update_benchmark:
    # Name the Job
    name: update benchmark every month
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i
      - name: system build deps
        run: sudo apt-get install -y build-essential gcc-multilib
      - run: |
          git clone https://github.com/bellard/quickjs.git && \
          cd quickjs && \
          make && \
          sudo make install
      - name: run benchmark and generate readme
        run: make
      - uses: EndBug/add-and-commit@v7
        with:
          message: 'update benchmark every month'
          add: '.'